test : 환경 변수 주입 테스트

diff --git a/.github/workflows/dev-frontend-ci-cd.yaml b/.github/workflows/dev-frontend-ci-cd.yaml
--- a/.github/workflows/dev-frontend-ci-cd.yaml
+++ b/.github/workflows/dev-frontend-ci-cd.yaml
@@ -29,15 +29,12 @@ jobs:
       - name: Debug environment variables
         run: |
           echo "REACT_APP_GITHUB_CLIENT_ID: $REACT_APP_GITHUB_CLIENT_ID"
-          echo "REACT_APP_REDIRECT_URI: $REACT_APP_REDIRECT_URI"
-          echo "REACT_APP_BACKEND_URI: $REACT_APP_BACKEND_URI"
-          echo "REACT_APP_BASE_URL: $REACT_APP_BASE_URL"
+          env | grep REACT_APP
         env:
           REACT_APP_GITHUB_CLIENT_ID: ${{ secrets.REACT_APP_GITHUB_CLIENT_ID }}
           REACT_APP_REDIRECT_URI: ${{ secrets.REACT_APP_REDIRECT_URI }}
           REACT_APP_BACKEND_URI: ${{ secrets.REACT_APP_BACKEND_URI }}
           REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
-      
       - name: Build
         run: CI=false npm run build
         env:
@@ -45,9 +42,9 @@ jobs:
           REACT_APP_REDIRECT_URI: ${{ secrets.REACT_APP_REDIRECT_URI }}
           REACT_APP_BACKEND_URI: ${{ secrets.REACT_APP_BACKEND_URI }}
           REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
-      
-      - name: Check build output
-        run: grep -r "REACT_APP_GITHUB_CLIENT_ID" build/ || echo "Not found in build"
+      - name: Check build contents
+        run: |
+          find build/ -type f -name "*.js" -exec grep -H "Ov23liQoOCN40W8vsEU0" {} \; || echo "Client ID not found in build"
       
         # SHA 앞 7자 추출
       - name: Extract short SHA
